eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true

logging:
  config: classpath:logback.xml

test:
  user:
    name: TEST
