test:
  user:
    name: book
    age: 22
spring:    
  # 配置服务中心地址
  cloud:
    config:
      # 服务中心地址
      uri: http://localhost:8887
      # yml尾缀{profile}
      profile: dev
      # git 分支
      #label: in-dev
      # 文件前缀{application}
      name: spring-book-service
