#端口号
spring:
  profiles:
    active: test
  application:
    name: spring-cloud-config-service
  cloud:
    config:
      label: in-dev
      profile: test
      name: spring-book-service
server:
  port: 8882

test:
  user:
    name: master
