#端口号
spring:
<<<<<<< HEAD
  application:
    name: spring-book-service
server:
  port: 8881

eureka:
  instance:
    hostname: localhost
  client:
    #由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
    #registerWithEureka: false
    #由于注册中心的职责就是维护服务实例,它并不需要去检索服务,所以也设置为false
    #fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
=======
  profiles:
    active: dev
  application:
    name: spring-cloud-config-service
  cloud:
    config:
      label: master
      profile: dev
      name: spring-book-service
server:
  port: 8881

>>>>>>> branch 'in-dev' of https://github.com/liuzunyu/springcloud.git
test:
  user:
<<<<<<< HEAD
    name: master-bus
    age: 88
=======
    name: in-dev-test
    age: 10
>>>>>>> branch 'in-dev' of https://github.com/liuzunyu/springcloud.git
