#端口号
spring:
  application:
    name: spring-cloud-book-service
  profiles:
    active: test
server:
  port: 8880

test:
  computer:
    name: github
  user:
    name: in-test-cloud-book
    password: 111
    age: 40
